intro/urls.py
from django.urls import path
from . import views

app_name = "intro"

urlpatterns = [
    path('', views.intro, name='intro'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('products/<str:category>/', views.items_category, name='products'),
    path('product/<int:id>/', views.item, name='product'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.buyer_user, name='user'),
    path('user/update/', views.update_password_buyer, name='update_password_buyer'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('delete_employee/<int:id>/', views.delete_employee, name='delete_employee'),
    path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('look_clients/', views.look_clients, name='look_clients'),
    path('comment/<int:product_id>/', views.comment, name='comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('favorite/<int:product_id>/', views.set_favorite_item, name='set_favorite_item'),
    path('delete_favorite/<int:product_id>/', views.delete_favorite_item, name='delete_favorite_item'),
    path('favorite/', views.favorite_items, name='favorite'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete_cart/<int:product_id>/', views.delete_cart, name='delete_cart'),
    path('add_one_product/<int:product_id>/', views.add_one_product, name='add_one_product'),
    path('remove_one_product/<int:product_id>/', views.remove_one_product, name='remove_one_product'),
    path('complete_buy/', views.complete_buy, name='complete_buy'),
    path('accept_sale/<int:id>/<str:text>/', views.accept_sale, name='accept_sale'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('forgot_username/', views.forgot_username, name='forgot_username'),
    path('stadistics_admin/', views.stadistics_admin, name='stadistics_admin'),
    path('get_products/<str:start_date>/<str:end_date>/', views.get_products, name='get_products'),
    path('get_favorite/', views.get_favorite, name='get_favorite'),
    path('get_sellers/', views.get_sellers, name='get_sellers'),
    path('get_products_cart/', views.get_products_cart, name='get_products_cart'),
    path('get_products_stars/<str:start_date>/<str:end_date>/', views.get_products_stars, name='get_products_stars'),
    path('search/', views.search_view, name='search')
]

majachi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from majachi import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.timezone import make_aware
from django.utils import timezone

from .models import ClientBuilder, ClientSellerRelation, CommentBuilder, Product_Quantity, ProductBuilder, Sale, User, Client, Category, Product, Seller, Comment, Favorite, Cart, UserBuilder
from django.core.mail import send_mail
from django.conf import settings
import random
import string

def login_view(request):
    session = request.session.get('redirect_to')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Autenticar el usuario
        try:
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                if session == 'register.html':
                    session = 'intro.html'

                return render(request, session or 'intro.html')
            else:
                return render(request, session or 'intro.html', {'error': 'Usuario o contraseña incorrectos'})
        except:
            return render(request, session or 'intro.html', {'error': 'Usuario o contraseña incorrectos'})
        
def intro(request):
    request.session['redirect_to'] = 'intro.html'
    return render(request, 'intro.html')

def items_category(request, category):
    products = Product.objects.filter(category=Category.objects.get(name=category))
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(products, 40)
        products = paginator.page(page)
    except:
        paginator = Paginator(products, 1)
        products = paginator.page(1)

    return render(request, 'items_category.html', {
        'url_name': 'products/' + category,
        'entity': products,
        'paginator': paginator
    })

def item(request, id):
    product = Product.objects.get(pk=id)

    # Sacar una media de las estrellas
    stars = 0
    for c in product.comments.all():
        stars += c.stars

    try:
        star = stars / product.comments.count()
    except:
        star = 0

    # Quitar los decimales
    star = int(star)

    # Ordenar de mas estrellas a menos estrellas
    comment = product.comments.all().order_by('-stars')

    # Comprobar si el producto está en favoritos
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)
        try:
            favorite = Favorite.objects.filter(user=user, product=product)
            if favorite:
                favorite = True
            else:
                favorite = False
        except:
            favorite = False
    else:
        favorite = False

    return render(request, 'item.html', {
        'product': product,
        "comments": comment,
        'star': star,
        'favorite': favorite
    })

def register(request):
    if request.user.is_authenticated:
        return render(request, 'intro.html', {
            'error': 'Ya has iniciado sesión'
        })
    request.session['redirect_to'] = 'register.html'
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        phone = request.POST.get('phone')

        if password == password2:
            user = UserBuilder().with_username(username).with_email(email).with_password(password).with_phone(phone).build()
            client = ClientBuilder().with_user(user).build()


            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, 'intro.html')
        else:
            return render(request, 'register.html', {
                'error': 'Las contraseñas no coinciden',
                'username': username,
                'email': email,
                'phone': phone
            })
    return render(request, 'register.html')

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, 'intro.html')
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })

def buyer_user(request):
    if request.user.is_authenticated:
        request.session['redirect_to'] = 'users/buyer_user.html'
        if request.method == 'POST':
            user = User.objects.get(pk=request.user.id)
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.username = request.POST.get('username')
            user.phone = request.POST.get('phone')
            user.save()
            client = Client.objects.get(user=user)
            client.principal_address = request.POST.get('principal_address')
            client.secondary_address = request.POST.get('secondary_address')
            client.no_house = request.POST.get('no_house')
            client.save()
            return render(request, 'users/buyer_user.html', {
                'success': 'Usuario actualizado correctamente',
            })
        else:
            if request.user.is_admin or request.user.is_seller:
                return render(request, 'users/buyer_user.html')
            else:
                # Poner categoría al usuario por respecto a ventas en un mes
                client = Client.objects.get(user=request.user)
                start_date = timezone.now() - datetime.timedelta(days=30)
                end_date = timezone.now()

                print("Depuración: Fecha de inicio:", start_date)
                print("Depuración: Fecha de fin:", end_date)

                try:
                    # Contar las ventas en el rango de fechas
                    sales_count = Sale.objects.filter(client=client.user, date__range=[start_date, end_date]).count()
                    print("Depuración: Conteo de ventas:", sales_count)
                    # Asignar categoría según la cantidad de ventas
                    if sales_count >= 10:
                        client.category = 'Oro'
                        client.save()
                        print("Depuración: Categoría cambiada a Oro")
                    elif sales_count >= 5:
                        client.category = 'Plata'
                        client.save()
                        print("Depuración: Categoría cambiada a Plata")
                    elif sales_count >= 2:
                        client.category = 'Bronce'
                        client.save()
                        print("Depuración: Categoría cambiada a Bronce")
                except Exception as e:
                    print(f"An error occurred: {e}")
                return render(request, 'users/buyer_user.html', {
                    'client': Client.objects.get(user=request.user)
                })
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })

    
def update_password_buyer(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            user = User.objects.get(pk=request.user.id)
            if not user.check_password(request.POST.get('password')):
                return render(request, 'users/buyer_user.html', {
                    'error': 'La contraseña actual no es correcta'
                })
            
            password = request.POST.get('password_change')
            password2 = request.POST.get('password_change2')
            if password == password2:
                user.set_password(password)
                user.save()
                logout(request)
                return render(request, 'intro.html', {
                    'success': 'Contraseña actualizada correctamente'
                })
            else:
                return render(request, 'users/buyer_user.html', {
                    'error': 'Las contraseñas no coinciden'
                })
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })
    
def admin_view(request):
    if request.user.is_authenticated and request.user.is_admin:
        if request.method == 'POST':
            id = request.POST.get('id_product')
            name = request.POST.get('name')
            price = request.POST.get('price')
            stock = request.POST.get('stock')
            description = request.POST.get('description')
            category = request.POST.get('category')
            photo = request.FILES.get('photo')

            if id:
                product = Product.objects.get(pk=id)
                product.name = name
                product.price = price
                product.stock = stock
                
                if description:
                    product.description = description

                if int(category) > 0:
                    product.category = Category.objects.get(pk=category)

                if photo:
                    product.photo = photo

                product.save()
                return render(request, 'users/admin.html', {
                    'success': 'Producto editado correctamente',
                    'sellers': Seller.objects.all(),
                    'categories': Category.objects.all(),
                    'products': Product.objects.all()
                })
            else:
                if category == 0:
                    return render(request, 'users/admin.html', {
                        'error': 'Debes seleccionar una categoría',
                        'sellers': Seller.objects.all(),
                        'categories': Category.objects.all(),
                        'products': Product.objects.all()
                    })

intro/templates/forgot_password.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Home Majach {% endblock %}

{% block body %}
<form action="{% url 'intro:forgot_password' %}" method="post" class="box-forgot">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <div class="col-12">
                <h1 data-section="forgot" data-value="forgot-password">Recuperar Usuario</h1>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-4 input_info">
                <label for="email" data-section="register" data-value="email"></label>
            </div>
            <div class="col-8 input_info">
                <input type="email" name="email" id="email" placeholder="Correo Electronico">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <button class="btn btn-primary" type="submit" data-section="forgot" data-value="password">Recuperar Usuario</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

intro/templates/forgot_username.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Home Majach {% endblock %}

{% block body %}
<form action="{% url 'intro:forgot_username' %}" method="post" class="box-forgot">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <div class="col-12">
                <h1 data-section="forgot" data-value="forgot-username">Recuperar Usuario</h1>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-4 input_info">
                <label for="email" data-section="register" data-value="email"></label>
            </div>
            <div class="col-8 input_info">
                <input type="email" name="email" id="email" placeholder="Correo Electronico">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <button class="btn btn-primary" type="submit" data-section="forgot" data-value="username">Recuperar Usuario</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

intro/templates/intro.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Home Majach {% endblock %}

{% block body %}
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner box-carousel">
        <div class="carousel-item active">
            <img src="{% static 'img/carousel/Banner-1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/carousel/Banner-2.jpg' %}" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="grid-container">
    {% for category in categories %}
    <div class="grid-item">
        <div class="container text-center">
            <div class="row row-cols-2">
                <div class="col">
                    <img class="box-img" src="{{ category.photo.url }}" class="img-fluid" alt="...">
                </div>
                <div class="col">
                    <h3 class="name-topic">{{ category.name }}</h3>
                </div>
                <div class="col">&nbsp;</div>
                <div class="col">
                    <a href="{% url 'intro:products' category.name %}" class="button_show_more">
                        <button data-section="layout" data-value="show-more"></button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

intro/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <base href="/">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <link rel="shortcut icon" href="{% static 'ico/Logo majach.ico' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar fixed-top sticky-top bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'intro:intro' %}">
                <img class="nav_logo" src="{% static 'img/Logo majach.jpg' %}" alt="Home" width="100">
            </a>
            <form action="{% url 'intro:search' %}" class="d-flex" method="post">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <input class="form-control me-2" type="search" name="search" aria-label="Search" placeholder="&#x1F50D; Search">
                        </div>
                    </div>
                </div>
            </form>

            <!-- Boton modal -->
            <div class="self_responsive_end">
                {% if not user.is_authenticated %}
                <button type="button" class="btn btn-primary login_button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" data-section="layout" data-value="login"></button>
                {% else %}
                    <div class="tree_buttons">
                        {% if is_seller %}
                            <a type="button" href="#" class="circular_btn">
                                <img src="{% static 'img/usuario-Freepik.png' %}" alt="photo_user" width="100">
                            </a>
                        {% elif is_admin %}
                            <a type="button" href="#" class="circular_btn">
                                <img src="{% static 'img/usuario-Freepik.png' %}" alt="photo_user" width="100">
                            </a>
                        {% else %}
                            {% if user.is_admin %}
                                <a type="button" href="{% url 'intro:stadistics_admin' %}" class="circular_btn">
                                    <img src="{% static 'img/grafico-circular-freepik.png' %}" alt="Favoritos" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:admin_view' %}" class="circular_btn">
                                    <img src="{% static 'img/setting-freepik.png' %}" alt="Carrito de compras" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:user' %}" class="circular_btn">
                                    <img src="{{ user.photo.url }}" alt="photo_user" width="100">
                                </a>
                            {% elif user.is_seller %}
                                <a type="button" href="{% url 'intro:favorite' %}" class="circular_btn">
                                    <img src="{% static 'img/favorito-Freepik.png' %}" alt="Favoritos" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:look_clients' %}" class="circular_btn">
                                    <img src="{% static 'img/setting-freepik.png' %}" alt="Carrito de compras" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:user' %}" class="circular_btn">
                                    <img src="{{ user.photo.url }}" alt="photo_user" width="100">
                                </a>
                            {% else %}
                                <a type="button" href="{% url 'intro:favorite' %}" class="circular_btn">
                                    <img src="{% static 'img/favorito-Freepik.png' %}" alt="Favoritos" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:cart' %}" class="circular_btn">
                                    <img src="{% static 'img/carrito-de-compras-Freepik.png' %}" alt="Carrito de compras" width="100">
                                </a>
                                <a type="button" href="{% url 'intro:user' %}" class="circular_btn">
                                    <img src="{{ user.photo.url }}" alt="photo_user" width="100">
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="button-sidebar" onclick="openSidebar(this)" id="sidebarButton">
            <span class="material-symbols-outlined">
                menu
            </span>
        </div>
    </nav>
    <nav id="sidebar">
        <ul>
            {% for category in categories %}
                <a href="{% url 'intro:products' category.name %}">
                    <li>{{ category.name }}</li>
                </a>
            {% endfor %}
        </ul>
    </nav>
    <main id="body">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% elif success %}
            <div class="alert alert-success" role="alert">
                {{ success }}
            </div>
        {% endif %}
        {% block body %} {% endblock %}
    </main>

    <!-- Seccion del modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="login_logo">
                        <img src="{% static 'img/Logo majach.jpg' %}" alt="majach" width="100">
                    </div>
                    <form action="{% url 'intro:login' %}" method="post">
                        {% csrf_token %}
                        <div class="form_login">
                            <div class="container">
                                <div class="row">
                                    <div class="col-4 input_info">
                                        <label for="username" data-section="layout" data-value="username"></label>
                                    </div>
                                    <div class="col-8 input_info">
                                        <input type="text" name="username" id="username" placeholder="Usuario">
                                    </div>
                                </div>
                            </div>
                            <div class="container">
                                <div class="row">
                                    <div class="col-4 input_info">
                                        <label for="password" data-section="layout" data-value="password"></label>
                                    </div>
                                    <div class="col-8 input_info">
                                        <input type="password" name="password" id="password" placeholder="Contraseña">
                                        <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password')">
                                            <span class="material-symbols-outlined">
                                                visibility
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
    
                            <div class="botton_login">
                                <button type="submit" data-section="layout" data-value="login"></button>
                            </div>
    
                            <div class="forgot_something">
                                <p><span data-section="layout" data-value="forgot-username"></span> <span><a href="{% url 'intro:forgot_username' %}" data-section="layout" data-value="link-username"></a></span></p>
                                <p><span data-section="layout" data-value="forgot-password"></span> <span><a href="{% url 'intro:forgot_password' %}" data-section="layout" data-value="link-password"></a></span></p>
                            </div>
                        </div>
                    </form>
                    <hr>
                    <div class="register_link">
                        <p><span data-section="layout" data-value="register"></span> <a data-section="layout" data-value="registrate" href="{% url 'intro:register' %}"></a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.5.0/echarts.min.js"></script>
    <script src="{% static 'js/ECharts.js' %}"> </script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/idiom.js' %}"></script>
    <script src="{% static 'js/errors.js' %}"></script>
</body>
</html>

intro/templates/register.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Registrar Majach {% endblock %}

{% block body %}
<div class="principal_info">
    <div class="container">
        <div class="row">
            <div class="col">
                <img class="majach_logo" src="{% static 'img/Logo majach.jpg' %}" alt="majach" width="100">
            </div>
            <div class="col">
                <h2 data-section="register" data-value="title"></h2>      
            </div>
            <div class="col">
                <a href="">&nbsp</a>
            </div>
        </div>
    </div>
</div>
<form action="{% url 'intro:register' %}" method="post">
    {% csrf_token %}
    <div class="register_view">
        <div id="form_register">
            <div class="container">
                <div class="row">
                    <div class="col-4 input_info">
                        <label data-section="layout" data-value="username"></label>
                    </div>
                    <div class="col-8 input_info">
                        <input type="text" name="username" id="username" placeholder="Usuario" value="{{ username }}">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-4 input_info">
                        <label for="email" data-section="register" data-value="email"></label>
                    </div>
                    <div class="col-8 input_info">
                        <input type="email" name="email" id="email" placeholder="Correo" value="{{ email }}">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-4 input_info">
                        <label for="password" data-section="layout" data-value="password"></label>
                    </div>
                    <div class="col-8 input_info">
                        <input type="password" name="password" id="password" placeholder="Contraseña">
                        <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password')">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-4 input_info">
                        <label for="password2" data-section="register" data-value="confirm-password"></label>
                    </div>
                    <div class="col-8 input_info">
                        <input type="password" name="password2" id="password2" placeholder="Contraseña">
                        <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password2')">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-4 input_info">
                        <label for="phone" data-section="register" data-value="phone"></label>
                    </div>
                    <div class="col-8 input_info">
                        <input type="number" name="phone" id="phone" placeholder="Celular" value="{{ phone }}" min="9" max="10">
                    </div>
                </div>
            </div>
    
            <div class="aligth_center">
                <button type="submit" class="register_button" data-section="register" data-value="register"></button>
            </div>
            <div class="aligth_center">
                <a href="{% url 'intro:intro' %}" class="register_button aligth_center" data-section="register" data-value="tienda"></a>
            </div>
        </div>
    </div>
</form>
{% endblock %}