intro/urls.py
from django.urls import path
from . import views

app_name = "intro"

urlpatterns = [
    path('', views.intro, name='intro'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('products/<str:category>/', views.items_category, name='products'),
    path('product/<int:id>/', views.item, name='product'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.buyer_user, name='user'),
    path('user/update/', views.update_password_buyer, name='update_password_buyer'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('delete_employee/<int:id>/', views.delete_employee, name='delete_employee'),
    path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('look_clients/', views.look_clients, name='look_clients'),
    path('comment/<int:product_id>/', views.comment, name='comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('favorite/<int:product_id>/', views.set_favorite_item, name='set_favorite_item'),
    path('delete_favorite/<int:product_id>/', views.delete_favorite_item, name='delete_favorite_item'),
    path('favorite/', views.favorite_items, name='favorite'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('delete_cart/<int:product_id>/', views.delete_cart, name='delete_cart'),
    path('add_one_product/<int:product_id>/', views.add_one_product, name='add_one_product'),
    path('remove_one_product/<int:product_id>/', views.remove_one_product, name='remove_one_product'),
    path('complete_buy/', views.complete_buy, name='complete_buy'),
    path('accept_sale/<int:id>/<str:text>/', views.accept_sale, name='accept_sale'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('forgot_username/', views.forgot_username, name='forgot_username'),
    path('stadistics_admin/', views.stadistics_admin, name='stadistics_admin'),
    path('get_products/<str:start_date>/<str:end_date>/', views.get_products, name='get_products'),
    path('get_favorite/', views.get_favorite, name='get_favorite'),
    path('get_sellers/', views.get_sellers, name='get_sellers'),
    path('get_products_cart/', views.get_products_cart, name='get_products_cart'),
    path('get_products_stars/<str:start_date>/<str:end_date>/', views.get_products_stars, name='get_products_stars'),
    path('search/', views.search_view, name='search')
]

majachi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from majachi import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.timezone import make_aware
from django.utils import timezone

from .models import ClientBuilder, ClientSellerRelation, CommentBuilder, Product_Quantity, ProductBuilder, Sale, User, Client, Category, Product, Seller, Comment, Favorite, Cart, UserBuilder
from django.core.mail import send_mail
from django.conf import settings
import random
import string

def login_view(request):
    session = request.session.get('redirect_to')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Autenticar el usuario
        try:
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                if session == 'register.html':
                    session = 'intro.html'

                return render(request, session or 'intro.html')
            else:
                return render(request, session or 'intro.html', {'error': 'Usuario o contraseña incorrectos'})
        except:
            return render(request, session or 'intro.html', {'error': 'Usuario o contraseña incorrectos'})
        
def intro(request):
    request.session['redirect_to'] = 'intro.html'
    return render(request, 'intro.html')

def items_category(request, category):
    products = Product.objects.filter(category=Category.objects.get(name=category))
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(products, 40)
        products = paginator.page(page)
    except:
        paginator = Paginator(products, 1)
        products = paginator.page(1)

    return render(request, 'items_category.html', {
        'url_name': 'products/' + category,
        'entity': products,
        'paginator': paginator
    })

def item(request, id):
    product = Product.objects.get(pk=id)

    # Sacar una media de las estrellas
    stars = 0
    for c in product.comments.all():
        stars += c.stars

    try:
        star = stars / product.comments.count()
    except:
        star = 0

    # Quitar los decimales
    star = int(star)

    # Ordenar de mas estrellas a menos estrellas
    comment = product.comments.all().order_by('-stars')

    # Comprobar si el producto está en favoritos
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)
        try:
            favorite = Favorite.objects.filter(user=user, product=product)
            if favorite:
                favorite = True
            else:
                favorite = False
        except:
            favorite = False
    else:
        favorite = False

    return render(request, 'item.html', {
        'product': product,
        "comments": comment,
        'star': star,
        'favorite': favorite
    })

def register(request):
    if request.user.is_authenticated:
        return render(request, 'intro.html', {
            'error': 'Ya has iniciado sesión'
        })
    request.session['redirect_to'] = 'register.html'
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        phone = request.POST.get('phone')

        if password == password2:
            user = UserBuilder().with_username(username).with_email(email).with_password(password).with_phone(phone).build()
            client = ClientBuilder().with_user(user).build()


            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, 'intro.html')
        else:
            return render(request, 'register.html', {
                'error': 'Las contraseñas no coinciden',
                'username': username,
                'email': email,
                'phone': phone
            })
    return render(request, 'register.html')

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, 'intro.html')
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })

def buyer_user(request):
    if request.user.is_authenticated:
        request.session['redirect_to'] = 'users/buyer_user.html'
        if request.method == 'POST':
            user = User.objects.get(pk=request.user.id)
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.username = request.POST.get('username')
            user.phone = request.POST.get('phone')
            user.save()
            client = Client.objects.get(user=user)
            client.principal_address = request.POST.get('principal_address')
            client.secondary_address = request.POST.get('secondary_address')
            client.no_house = request.POST.get('no_house')
            client.save()
            return render(request, 'users/buyer_user.html', {
                'success': 'Usuario actualizado correctamente',
            })
        else:
            if request.user.is_admin or request.user.is_seller:
                return render(request, 'users/buyer_user.html')
            else:
                # Poner categoría al usuario por respecto a ventas en un mes
                client = Client.objects.get(user=request.user)
                start_date = timezone.now() - datetime.timedelta(days=30)
                end_date = timezone.now()

                print("Depuración: Fecha de inicio:", start_date)
                print("Depuración: Fecha de fin:", end_date)

                try:
                    # Contar las ventas en el rango de fechas
                    sales_count = Sale.objects.filter(client=client.user, date__range=[start_date, end_date]).count()
                    print("Depuración: Conteo de ventas:", sales_count)
                    # Asignar categoría según la cantidad de ventas
                    if sales_count >= 10:
                        client.category = 'Oro'
                        client.save()
                        print("Depuración: Categoría cambiada a Oro")
                    elif sales_count >= 5:
                        client.category = 'Plata'
                        client.save()
                        print("Depuración: Categoría cambiada a Plata")
                    elif sales_count >= 2:
                        client.category = 'Bronce'
                        client.save()
                        print("Depuración: Categoría cambiada a Bronce")
                except Exception as e:
                    print(f"An error occurred: {e}")
                return render(request, 'users/buyer_user.html', {
                    'client': Client.objects.get(user=request.user)
                })
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })

    
def update_password_buyer(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            user = User.objects.get(pk=request.user.id)
            if not user.check_password(request.POST.get('password')):
                return render(request, 'users/buyer_user.html', {
                    'error': 'La contraseña actual no es correcta'
                })
            
            password = request.POST.get('password_change')
            password2 = request.POST.get('password_change2')
            if password == password2:
                user.set_password(password)
                user.save()
                logout(request)
                return render(request, 'intro.html', {
                    'success': 'Contraseña actualizada correctamente'
                })
            else:
                return render(request, 'users/buyer_user.html', {
                    'error': 'Las contraseñas no coinciden'
                })
    else:
        return render(request, 'intro.html', {
            'error': 'Debes iniciar sesión para acceder a esta página'
        })
    
def admin_view(request):
    if request.user.is_authenticated and request.user.is_admin:
        if request.method == 'POST':
            id = request.POST.get('id_product')
            name = request.POST.get('name')
            price = request.POST.get('price')
            stock = request.POST.get('stock')
            description = request.POST.get('description')
            category = request.POST.get('category')
            photo = request.FILES.get('photo')

            if id:
                product = Product.objects.get(pk=id)
                product.name = name
                product.price = price
                product.stock = stock
                
                if description:
                    product.description = description

                if int(category) > 0:
                    product.category = Category.objects.get(pk=category)

                if photo:
                    product.photo = photo

                product.save()
                return render(request, 'users/admin.html', {
                    'success': 'Producto editado correctamente',
                    'sellers': Seller.objects.all(),
                    'categories': Category.objects.all(),
                    'products': Product.objects.all()
                })
            else:
                if category == 0:
                    return render(request, 'users/admin.html', {
                        'error': 'Debes seleccionar una categoría',
                        'sellers': Seller.objects.all(),
                        'categories': Category.objects.all(),
                        'products': Product.objects.all()
                    })

intro/templates/users/buyer_user.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    Perfil {{ user.username }}
{% endblock %}

{% block body %}
<div class="principal_info">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <img class="majach_logo" src="{{ user.photo.url }}" alt="{{ user.username }}" width="100">
            </div>
            <div class="col-5 text-center">
                {% if user.first_name != "" or user.last_name != "" %}
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                    <p>{{ client.category }}</p>
                {% else %}
                    <h2>{{ user.username }}</h2>
                {% endif %}
            </div>
            <div class="col-3 text-center">
                <a class="register_button" href="{% url 'intro:logout' %}" data-section="layout" data-value="logout"></a>
                <a class="responsive_register_button" href="{% url 'intro:logout' %}">
                    <span class="material-symbols-outlined" style="color: white;">
                        power_settings_new
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>

<h4 class="edit_info" data-section="personal-page" data-value="edit-information"></h4>
<div class="container text-center">
    <div class="row full-screen-responsive">
        <div class="col">
            <form action="{% url 'intro:user' %}" method="post">
                {% csrf_token %}
                <h3 data-section="personal-page" data-value="information"></h3>
                <div class="user_view">
                    <div id="user_form">
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="first_name" data-section="admin" data-value="names"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="first_name" id="first_name" placeholder="Nombres" value="{{ user.first_name }}" {% if user.is_admin or user.is_seller %} readonly {% endif %}>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="last_name" data-section="admin" data-value="last"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="last_name" id="last_name" placeholder="Apellidos" value="{{ user.last_name }}" {% if user.is_admin or user.is_seller %} readonly {% endif %}>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="username" data-section="layout" data-value="username"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="username" id="username" placeholder="Usuario" value="{{ user.username }}">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="phone" data-section="register" data-value="phone"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="number" name="phone" id="phone" placeholder="Usuario" value="{{ user.phone }}">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="email" data-section="register" data-value="email"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="email" name="email" id="email" placeholder="Correo" value="{{ user.email }}" readonly>
                                </div>
                            </div>
                        </div>
                        {% if user.is_admin or user.is_seller %}
                        {% else %}
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="principal_address" data-section="personal-page" data-value="principal-streret"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="principal_address" id="principal_address" placeholder="Calle principal" value="{{ client.principal_address }}">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="secondary_address" data-section="personal-page" data-value="secondary-street"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="secondary_address" id="secondary_address" placeholder="Calle secundaria" value="{{ client.secondary_address }}">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 input_info">
                                    <label for="no_house" data-section="personal-page" data-value="no-house"></label>
                                </div>
                                <div class="col-8 input_info">
                                    <input type="text" name="no_house" id="no_house" placeholder="Numero de casa" value="{{ client.no_house }}">
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="aligth_center">
                            <button type="submit" class="register_button" data-section="personal-page" data-value="update-information"></button>
                        </div>
                    </div>
                </div>     
            </form>
        </div>
        <div class="col">
            <form action="{% url 'intro:update_password_buyer' %}" method="post">
                {% csrf_token %}
                <h3>Actualizar contraseña</h3>
                <div class="user_view">
                    <div id="user_form">
                        <div class="container">
                            <div class="row">
                                <div class="col-5 input_info">
                                    <label for="password" data-section="personal-page" data-value="actual-password"></label>
                                </div>
                                <div class="col-6 input_info">
                                    <input type="password" name="password" id="password" placeholder="Contraseña">
                                    <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password')">
                                        <span class="material-symbols-outlined">
                                            visibility
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-5 input_info">
                                    <label for="password_change" data-section="personal-page" data-value="new-password"></label>
                                </div>
                                <div class="col-6 input_info">
                                    <input type="password" name="password_change" id="password_change" placeholder="Contraseña">
                                    <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password_change')">
                                        <span class="material-symbols-outlined">
                                            visibility
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-5 input_info">
                                    <label for="password_change2" data-section="register" data-value="confirm-password"></label>
                                </div>
                                <div class="col-6 input_info">
                                    <input type="password" name="password_change2" id="password_change2" placeholder="Contraseña">
                                    <button type="button" class="toggle-password" onclick="togglePasswordVisibility('password_change2')">
                                        <span class="material-symbols-outlined">
                                            visibility
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="aligth_center">
                            <button type="submit" class="register_button" data-section="personal-page" data-value="change-password"></button>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <a href="{% url 'intro:favorite' %}" class="register_button bg-none">
                                        <img src="{% static 'img/favorito-Freepik.png' %}" alt="Favoritos" width="100">
                                        <br><br>
                                        <h4 data-section="personal-page" data-value="favorite"></h4>
                                    </a>
                                </div>
                                <div class="col">
                                    <a href="{% url 'intro:cart' %}" class="register_button bg-none">
                                        <img src="{% static 'img/carrito-de-compras-Freepik.png' %}" alt="Carrito de compras" width="100">
                                        <br><br>
                                        <h4 data-section="personal-page" data-value="cart"></h4>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

intro/templates/users/employee.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    Ver clientes
{% endblock %}

{% block body %}
<div class="principal_info">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <img class="majach_logo" src="{{ user.photo.url }}" alt="{{ user.username }}" width="100">
            </div>
            <div class="col-5 text-center">
                {% if user.first_name != "" or user.last_name != "" %}
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                    <h2> <span data-section="employee" data-value="code">Código:</span> {{ employee.code_seller }}</h2>
                {% else %}
                    <h2>{{ user.username }}</h2>
                    <h2> <span data-section="employee" data-value="code">Código:</span> {{ employee.code_seller }}</h2>
                {% endif %}  
            </div>
            <div class="col-3 text-center">
                <a class="register_button" href="{% url 'intro:logout' %}" data-section="layout" data-value="logout"></a>
                <a class="responsive_register_button" href="{% url 'intro:logout' %}">
                    <span class="material-symbols-outlined" style="color: white;">
                        power_settings_new
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>

<h3>Agregar nuevos cliente</h3>
<div class="user_view">
    <div id="user_form">
        <div class="aligth_center">
            <button type="button" class="register_button text-center" data-bs-toggle="modal" data-bs-target="#addClient">
                <div class="container text-center">
                    <div class="row">
                        <div class="col">Agregar</div>
                        <div class="col"><span class="material-symbols-outlined">person_add</span></div>
                    </div>
                </div>
            </button>
        </div>
    </div>
    <h3>Lista de compradores</h3>
    <table class="table table-bordered border-dark">
        <thead>
            <tr>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="username"></th>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="email"></th>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="phone"></th>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="see_products"></th>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="price"></th>
                <th scope="col" style="background-color: #466475;" data-section="employee" data-value="mark_done"></th>
            </tr>
        </thead>
        <tbody>
            {% for client in entity %}
                <tr>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        {{ client.client.user.username }}
                    </td>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        {{ client.client.user.email }}
                    </td>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        {{ client.client.user.phone }}
                    </td>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        {% for products in client.Product_Quantity.all %}
                            {{ products.product.name }}: {{ products.quantity }}<br>
                        {% endfor %}
                    </td>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        $ {{ client.total }}
                    </td>
                    <td {% if not client.done_sale %} style="background-color: rgb(221, 84, 84);" {% endif %}>
                        <form action="{% url 'intro:accept_sale' client.id 'entregado' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn-buyproduct margin-bottom" data-section="cart" data-value="done"></button>
                        </form>
                        <form action="{% url 'intro:accept_sale' client.id 'rechazado' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn-cancel" data-section="cart" data-value="not-done"></button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div>
    {% include 'paginator.html' %}
</div>
{% endblock %}

intro/templates/users/favorite.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Home Majach {% endblock %}

{% block body %}
<h2  data-section="favorite" data-value="favorite"></h2>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for favorite in favorites %}
        <div class="conatiner-ineer">
            <a href="{% url 'intro:product' favorite.product.id %}" class="col box-product">
                <div class="row row-cols-1">
                    <div class="container text-center">
                        <div class="col">
                            <div class="box-items">
                                <img src="{{ favorite.product.photo.url }}" alt="{{ product.name }}" width="100">
                            </div>
                        </div>
                        <div class="col">
                            <h3 class="cl-white">{{ favorite.product.name }}</h3>
                        </div>
                        <div class="col">
                            <div class="button-class">
                                <button class="item-cash">${{ favorite.product.price | floatformat:2 }}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}